// todolist-angular/src/app/component/list/list.component.ts
import { Component, computed, inject, OnInit, Signal, signal, WritableSignal } from '@angular/core';
import { TodoService } from '../../service/todo.service';
import { Todo } from '../../type/todo.type';
import { CommonModule, DatePipe } from '@angular/common';

@Component({
  selector: 'app-list',
  imports: [DatePipe],
  templateUrl: './list.component.html',
  styleUrl: './list.component.scss'
})
export class ListComponent implements OnInit {
  todoService=inject(TodoService)
  todoList:WritableSignal<Todo[]> = signal([]);
  remainingTodo: Signal<number> = computed(
    ()=>this.todoList().filter((t) => !t.completed).length
  )



  ngOnInit(): void {
    this.getTodoList();
  }

  getTodoList(): void {
    this.todoList = this.todoService.getTodoList();
  }

  toggleCompleteStatus(todo: Todo): void {
    this.todoService.toggleCompleteStatus(todo);
  }

  removeTodo(todo: Todo): void {
    this.todoService.removeTodo(todo);
  }

  removeCompletedTodo(): void {
    this.todoService.removeCompletedTodo();
  }


}

<ul class="todo-list">
  @for (todo of todoList(); track $index) {

  <li>
    <div class="view">
      <input
        class="toggle"
        type="checkbox"
        (click)="toggleCompleteStatus(todo)"
      />
      <label [class.completed]="todo.completed">{{ todo.content }}/{{todo.create|date}}</label>
      <button class="destroy" (click)="removeTodo(todo)"></button>
    </div>
  </li>
  }
</ul>
<footer class="footer">
  <span class="todo-count"
    ><strong>{{ remainingTodo() }}</strong> left</span
  >
  <button class="clear-completed" (click)="removeCompletedTodo()">
    Clear completed
  </button>
</footer>

// todolist-react/src/app/list/page.tsx
"use client";
import { useMemo } from "react";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../store";
import { toggleTodo, removeCompletedTodo, removeTodo } from "../todoSlice";

function useFormattedDate(date: Date): string {
  return useMemo(() => {
    return `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
  }, [date]);
}

export default function Page() {
  const todos = useSelector((state: RootState) => state.todos);
  const dispatch = useDispatch();

  const remainingTodo = todos.filter((t) => !t.completed).length;
  const formattedDate = useFormattedDate(new Date());
  return (
    <div>
      <ul className="todo-list">
        {todos.map((todo) => (
          <li key={todo.id}>
            <div className="view">
              <input
                className="toggle"
                type="checkbox"
                onClick={() => dispatch(toggleTodo(todo.id))}
              />
              <label className={todo.completed ? "completed" : ""}>
                {todo.content}/ {formattedDate}
              </label>
              <button
                className="destroy"
                onClick={() => dispatch(removeTodo(todo.id))}
              ></button>
            </div>
          </li>
        ))}
      </ul>
      <footer className="footer">
        <span className="todo-count">
          <strong> {remainingTodo} </strong> left
        </span>
        <button
          className="clear-completed"
          onClick={() => dispatch(removeCompletedTodo())}
        >
          Clear completed
        </button>
      </footer>
    </div>
  );
}
